# Generated by Django 4.0.3 on 2022-03-19 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_inadimplencia', models.CharField(max_length=255)),
                ('tempo_de_inadimplencia', models.DateField()),
                ('valor_do_aluguel', models.CharField(max_length=255)),
                ('date_aluguel', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
