# Generated by Django 4.0.3 on 2022-03-20 01:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitnet',
            name='date_aluguel',
        ),
        migrations.RemoveField(
            model_name='kitnet',
            name='status_inadimplencia',
        ),
        migrations.RemoveField(
            model_name='kitnet',
            name='tempo_de_inadimplencia',
        ),
        migrations.RemoveField(
            model_name='kitnet',
            name='valor_do_aluguel',
        ),
        migrations.AddField(
            model_name='inquilino',
            name='date_aluguel',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='status_inadimplencia',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquilino',
            name='tempo_de_inadimplencia',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquilino',
            name='valor_do_aluguel',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
