# Generated by Django 4.0.3 on 2022-03-20 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0002_remove_kitnet_date_aluguel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='date_aluguel',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
    ]
