# Generated by Django 4.0.3 on 2022-03-20 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0003_alter_inquilino_date_aluguel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquilino',
            name='date_aluguel',
        ),
        migrations.AddField(
            model_name='inquilino',
            name='ultimo_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
            preserve_default=False,
        ),
    ]
