# Generated by Django 4.0.3 on 2022-03-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0004_remove_inquilino_date_aluguel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='ultimo_pagamento',
            field=models.DateField(blank=True),
        ),
    ]
