# Generated by Django 4.0.3 on 2022-03-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0005_alter_inquilino_ultimo_pagamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitnet',
        ),
        migrations.AddField(
            model_name='inquilino',
            name='tamanho_do_kitnet',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
