# Generated by Django 4.0.3 on 2022-03-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0006_delete_kitnet_inquilino_tamanho_do_kitnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='status_inadimplencia',
            field=models.CharField(choices=[('S', 'ADIMPLENTE'), ('N', 'INADIMPLENTE')], max_length=15),
        ),
    ]
