# Generated by Django 4.0.3 on 2022-03-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0007_alter_inquilino_status_inadimplencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='status_inadimplencia',
            field=models.CharField(choices=[('ADIMPLENTE', 'ADIMPLENTE'), ('INADIMPLENTE', 'INADIMPLENTE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='tamanho_do_kitnet',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Medio', 'Medio'), ('Grande', 'Grande')], max_length=10),
        ),
    ]
