# Generated by Django 4.0.3 on 2022-03-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0008_alter_inquilino_status_inadimplencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquilino',
            old_name='status_inadimplencia',
            new_name='status_de_pagamentos',
        ),
    ]
