# Generated by Django 4.0.3 on 2022-03-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0009_rename_status_inadimplencia_inquilino_status_de_pagamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='status_de_pagamentos',
            field=models.CharField(choices=[('ADIMPLENTE', 'ADIMPLENTE'), ('INADIMPLENTE', 'INADIMPLENTE')], default='ADIMPLENTE', max_length=15),
        ),
    ]
