# Generated by Django 4.0.3 on 2022-03-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0010_alter_inquilino_status_de_pagamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquilino',
            name='tempo_de_inadimplencia',
        ),
    ]
