# Generated by Django 4.0.3 on 2022-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0011_remove_inquilino_tempo_de_inadimplencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='valor_do_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
