# Generated by Django 4.0.3 on 2022-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inadimplentes', '0013_inquilino_meses_de_inadimplencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='meses_de_inadimplencia',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
